var videoPlaylist = [
	{ id: 'lt-y8iwJQSc', start: 1, end: 288, title: 'Spinster - Earth Bleeds', artist: 'Spinster', genre: '' },
	{ id: 'OOfSGI4Btgc', start: 1, end: 244, title: 'Jock and Mitch - Trad Medley', artist: 'Jock and Mitch', genre: '' },
	{ id: 'mq9IPsSOPuI', start: 1, end: 193, title: 'Glad Rabbit - Talk About It', artist: 'Glad Rabbit', genre: '' },
	{ id: '_6mM_ExR5JI', start: 1, end: 228, title: 'Cox\'s Orange - Cavalier', artist: 'Cox\'s Orange', genre: '' },
	{ id: 'oWUiZzIbS7E', start: 1, end: 266, title: 'Pearl Street - Medusa', artist: 'Pearl Street', genre: '' },
	{ id: 'iv6IMoUcN-g', start: 1, end: 243, title: 'Fre3dom - Back to the Beginning Again (N&C2021)', artist: 'Fre3dom', genre: '' },
	{ id: 'Kc8E-kyzJ5I', start: 1, end: 309, title: 'The Dragonfly Rustlers - Avalon', artist: 'The Dragonfly Rustlers', genre: '' },
	{ id: 'xxLB347WgQk', start: 1, end: 185, title: 'Capt Spoonbill & the Hoiho - The Auld Triangle (N&C22)', artist: 'Capt Spoonbill & the Hoiho', genre: '' },
	{ id: 'GfjhgRoRMuE', start: 1, end: 171, title: 'Katie Nimmo - Jokes On You (N&C2021)', artist: 'Katie Nimmo', genre: '' },
	{ id: 'tyj_BaDuT3U', start: 1, end: 267, title: 'Aart Smith - Forgot to Grow Old (N&C22)', artist: 'Aart Smith', genre: '' },
	{ id: '_kFy8W0x3PM', start: 1, end: 310, title: 'Flying Man - Under The Stars (N&C22)', artist: 'Flying Man', genre: '' },
	{ id: 'uSWF8XlUO30', start: 1, end: 240, title: 'Goeknil M Biner & Tom McGrath - Music for a While', artist: 'Goeknil M Biner & Tom McGrath', genre: '' },
	{ id: 'kG5jMID-fMU', start: 1, end: 195, title: 'Natasha Manowitz - Four Pooh Stories', artist: 'Natasha Manowitz', genre: '' },
	{ id: '076yA7GexQ0', start: 1, end: 213, title: 'Haszari - Excerpt (N&C22)', artist: 'Haszari', genre: '' },
	{ id: 'X_5XVdbeo6U', start: 1, end: 330, title: 'The Unfortunate Repercussions - 1001 Nights', artist: 'The Unfortunate Repercussions', genre: '' },
	{ id: 'gGcxU9uUbaA', start: 1, end: 266, title: 'Ed Zuccollo - Improv (Excerpt)', artist: 'Ed Zuccollo', genre: '' },
	{ id: 'jAB4Qw-R-hw', start: 1, end: 224, title: 'The Bamboo - Hell Is...', artist: 'The Bamboo', genre: '' },
	{ id: 'jQ8CcJ-bBx4', start: 1, end: 286, title: 'The Phil Corfield Band - Loneliness & Dreams', artist: 'The Phil Corfield Band', genre: '' },
	{ id: '8EJOhPZKgeo', start: 1, end: 238, title: 'The Flukes - So True', artist: 'The Flukes', genre: '' },
	{ id: 'OEVJ0eB1xoI', start: 1, end: 184, title: 'Pottley Blues Collective - I Want You Here With Me (N&C2021)', artist: 'Pottley Blues Collective', genre: '' },
	{ id: 'CvBDbzauWew', start: 1, end: 243, title: 'Katie Raven - Why Do I Leave?', artist: 'Katie Raven', genre: '' },
	{ id: '9d8fE8HKK5Y', start: 1, end: 291, title: 'Koputai People\'s Party - Millionaire (N&C2021)', artist: 'Koputai People\'s Party', genre: '' },
	{ id: 'ssmpU9-fLSk', start: 1, end: 226, title: 'Bella Phillips - All I Want (N&C2021)', artist: 'Bella Phillips', genre: '' },
	{ id: 'OX6H3_n46r8', start: 1, end: 182, title: 'Bronwyn - Quarter Life Crisis', artist: 'Bronwyn', genre: '' },
	{ id: 'w4O7xSTCIGM', start: 1, end: 228, title: 'James Constable - Both Your Hands (N&C22)', artist: 'James Constable', genre: '' },
	{ id: '5ZYCq6dZX50', start: 1, end: 300, title: 'Person Will - Good Luck', artist: 'Person Will', genre: '' },
	{ id: 'LMTtRtxm9f4', start: 1, end: 214, title: 'Shakes - Stay In Bed', artist: 'Shakes', genre: '' },
	{ id: 'hiKImrvf9RY', start: 1, end: 259, title: 'James Dignan - She\'s the One', artist: 'James Dignan', genre: '' },
	{ id: 'j6S_h_0HiRU', start: 1, end: 221, title: 'Em and Me - Fairy Bread (N&C2021)', artist: 'Em and Me', genre: '' },
	{ id: 'CDEDDKvuecA', start: 1, end: 168, title: 'Spinster - Touch', artist: 'Spinster', genre: '' },
	{ id: 'owIjLCmQeVw', start: 1, end: 212, title: 'Jack Ringhand - Reno', artist: 'Jack Ringhand', genre: '' },
	{ id: 'Twq0A9RpPvM', start: 1, end: 155, title: 'VTMNK - Heatwave', artist: 'VTMNK', genre: '' },
	{ id: 'fZtdcpqbYDU', start: 1, end: 161, title: 'Rainbow Rosalind - Kia Ora', artist: 'Rainbow Rosalind', genre: '' },
	{ id: 'Wrsjxf4ftWc', start: 1, end: 250, title: 'Humboldt - Empty as a Pocket', artist: 'Humboldt', genre: '' },
	{ id: 'jIXR0cuekC4', start: 1, end: 109, title: 'Lil Spooky Band - The Flying Tea Bag', artist: 'Lil Spooky Band', genre: '' },
	{ id: 'dgjH-SwwgKM', start: 1, end: 264, title: 'Jimmy Higgs - Breathe Boy (N&C2021)', artist: 'Jimmy Higgs', genre: '' },
	{ id: 'JupxzihmAfE', start: 1, end: 358, title: 'Dee Street Blues - Sailin\' On The Sea (N&C2021)', artist: 'Dee Street Blues', genre: '' },
	{ id: 'pfllpgoK6rI', start: 1, end: 144, title: 'Robots In Love - Extraordinary Life', artist: 'Robots In Love', genre: '' },
	{ id: 'Amz155JtpV4', start: 1, end: 195, title: 'Agent Ewok - Babble', artist: 'Agent Ewok', genre: '' },
	{ id: 'yidc3ca7tSM', start: 1, end: 260, title: 'The Pottley Blues Collective - One Last Look At You', artist: 'The Pottley Blues Collective', genre: '' },
	{ id: 'gBc8FdYTl14', start: 1, end: 201, title: 'Robots In Love - Pure Love', artist: 'Robots In Love', genre: '' },
	{ id: 'beN1AcnxP7I', start: 1, end: 241, title: 'Both Sides of the Line - Peace (N&C2021)', artist: 'Both Sides of the Line', genre: '' },
	{ id: 'h3ppdErdW8o', start: 1, end: 352, title: 'DH Loops - Improv (Excerpt)', artist: 'DH Loops', genre: '' },
	{ id: 'MfKJRNDneVE', start: 1, end: 201, title: 'Soaked Oats - Blood Red Sentimental Blues', artist: 'Soaked Oats', genre: '' },
	{ id: 'GAFRkfCM3MA', start: 1, end: 255, title: 'McStew - Will of the People (N&C2021)', artist: 'McStew', genre: '' },
	{ id: 'X8Mr0HVpz3M', start: 1, end: 233, title: 'Last Chance Dogs - Out Of My League', artist: 'Last Chance Dogs', genre: '' },
	{ id: 'idtE1cwnSCA', start: 1, end: 151, title: 'Bb6 - I Can See Clearly Now', artist: 'Bb6', genre: '' },
	{ id: '_fHPVhyOuzw', start: 1, end: 157, title: 'Paul S Allen - Stay', artist: 'Paul S Allen', genre: '' },
	{ id: 'jpPDNvFZlj8', start: 1, end: 235, title: 'The Doo Rays - Time On Your Hands - 360', artist: 'The Doo Rays', genre: '' },
	{ id: 'r37Y9DpL4VQ', start: 1, end: 263, title: 'Whaea Soul - Don\'t Shut Life Out', artist: 'Whaea Soul', genre: '' },
	{ id: '27oUgbbuSQQ', start: 1, end: 275, title: 'The Doll Drums - Just Another Jungle Closing In', artist: 'The Doll Drums', genre: '' },
	{ id: 'NGPWRPLfQSM', start: 1, end: 208, title: 'Karthartipuss - Kiss Me K8', artist: 'Karthartipuss', genre: '' },
	{ id: 'VAT8VYu4GoM', start: 1, end: 256, title: 'The Mason Cooper Disaster - Take What You Want (N&C22)', artist: 'The Mason Cooper Disaster', genre: '' },
	{ id: '8vBzzwBdJ6Q', start: 1, end: 218, title: 'Dee Street Blues - Show Me The Love', artist: 'Dee Street Blues', genre: '' },
	{ id: 'a7L_DTGjxEk', start: 1, end: 210, title: 'Boaz Anema - History (N&C22)', artist: 'Boaz Anema', genre: '' },
	{ id: 'N1Y7NgD7cao', start: 1, end: 365, title: 'Mosaic Sky - Not OK (N&C2021)', artist: 'Mosaic Sky', genre: '' },
	{ id: 'CbKWwVaCgJQ', start: 1, end: 192, title: 'Boaz Anema - Backwater', artist: 'Boaz Anema', genre: '' },
	{ id: 'e2DTWV87Cn4', start: 1, end: 192, title: 'Concrete Grady - The Waters are Rising', artist: 'Concrete Grady', genre: '' },
	{ id: 'CIAhxZDuMMM', start: 1, end: 283, title: 'Soaked Oats - My Mud, Your Shoes', artist: 'Soaked Oats', genre: '' },
	{ id: '1A2wncPQ6BU', start: 1, end: 117, title: 'Your Face - Mind Control (N&C2021)', artist: 'Your Face', genre: '' },
	{ id: 'tlDYOS468Fg', start: 1, end: 317, title: 'Donna Dean - Way Too Wide', artist: 'Donna Dean', genre: '' },
	{ id: 'hnPO_VgliCg', start: 1, end: 235, title: 'Paul S Allen - Save Me (N&C22)', artist: 'Paul S Allen', genre: '' },
	{ id: 'hc1BsWswAR0', start: 1, end: 242, title: 'Cassandra Saunders - Thinking Out Loud', artist: 'Cassandra Saunders', genre: '' },
	{ id: 'AhxB0KBcBfk', start: 1, end: 349, title: 'The Mentalist Collective - Need a Little Time Away', artist: 'The Mentalist Collective', genre: '' },
	{ id: 'FzY7d6Qy6sY', start: 1, end: 213, title: 'Person Will - Aim Hi', artist: 'Person Will', genre: '' },
	{ id: 'wKAkTyWgzEo', start: 1, end: 193, title: 'The Phil Corfield Band - I Would Still Stand Up Somehow', artist: 'The Phil Corfield Band', genre: '' },
	{ id: 'oMQ43-uBPv4', start: 1, end: 235, title: 'Both Sides Of The Line - I love my Dahlias (N&C22)', artist: 'Both Sides Of The Line', genre: '' },
	{ id: 'qlnsuOCbVWU', start: 1, end: 286, title: 'Jackson Caine - Turn the Page', artist: 'Jackson Caine', genre: '' },
	{ id: 'slUPVUbU06o', start: 1, end: 271, title: 'Julian Temple - Orient Express', artist: 'Julian Temple', genre: '' },
	{ id: 'uNeMU86G2-0', start: 1, end: 174, title: 'Grexit No Grexit - Mega Low Media (N&C2021)', artist: 'Grexit No Grexit', genre: '' },
	{ id: '9DDQ9R5c6xg', start: 1, end: 225, title: 'The INTERSECTIONists - Falling Under Foot', artist: 'The INTERSECTIONists', genre: '' },
	{ id: '5VuPGFHbNnM', start: 1, end: 175, title: 'Seafog - Song of Hairless Ape', artist: 'Seafog', genre: '' },
	{ id: 'm2Ual7BzzT4', start: 1, end: 186, title: 'James Dignan - San Francisco Freeway', artist: 'James Dignan', genre: '' },
	{ id: 'GX-e_ykUGf4', start: 1, end: 165, title: 'SeaFog - Sticks and Stones', artist: 'SeaFog', genre: '' },
	{ id: 'hg8BNErg2v4', start: 1, end: 246, title: 'Trent Hawthorne - Mr Delay', artist: 'Trent Hawthorne', genre: '' },
	{ id: 'BkHAycTIrZU', start: 1, end: 240, title: 'Samuel Leaper', artist: 'Samuel Leaper', genre: '' },
	{ id: 'Vfun0DNzz_o', start: 1, end: 175, title: 'Koputai Peoples Party - Mama Knows Best (N&C22)', artist: 'Koputai Peoples Party', genre: '' },
	{ id: 'IJJPXX1As04', start: 1, end: 201, title: 'The Mentalist Collective - I Can\'t Believe It', artist: 'The Mentalist Collective', genre: '' },
	{ id: 'vB3dn2TRt4U', start: 1, end: 149, title: 'Xalotl - Palm Springs', artist: 'Xalotl', genre: '' },
	{ id: 'bos5gfLrD2k', start: 1, end: 227, title: 'Concrete Grady - Beloved', artist: 'Concrete Grady', genre: '' },
	{ id: 'Ftp1ly7Jfwk', start: 1, end: 315, title: 'Dee Street Blues - Here She Comes', artist: 'Dee Street Blues', genre: '' },
	{ id: 'HzSun76jlu0', start: 1, end: 250, title: 'Trent Hawthorne - The Letters', artist: 'Trent Hawthorne', genre: '' },
	{ id: 'Iv8O-uPDov8', start: 1, end: 128, title: 'Tabitha Littlejohn - Leveraging (N&C2021)', artist: 'Tabitha Littlejohn', genre: '' },
	{ id: 'NcVPNxHKTKc', start: 1, end: 218, title: 'Black Boy Peaches - Bulletproof', artist: 'Black Boy Peaches', genre: '' },
	{ id: 'HMcK3wms-98', start: 1, end: 171, title: 'ShelleyJ - Take a Look at a Library Book', artist: 'ShelleyJ', genre: '' },
	{ id: 'ZV4bjXkjZ48', start: 1, end: 157, title: 'Bill Martin - Mood Indigo (Duke Ellington)', artist: 'Bill Martin', genre: '' },
	{ id: 'HayKrYXi1EA', start: 1, end: 245, title: 'Phil Corfield Band - Somewhere Rings A Bell - Nook and Cranny Festival 2016', artist: 'Phil Corfield Band', genre: '' },
	{ id: 'rFLSz5QUcGs', start: 1, end: 191, title: 'Valley Bluegrass - Foggy Mountain Breakdown', artist: 'Valley Bluegrass', genre: '' },
	{ id: '23oBX0xZy2o', start: 1, end: 203, title: 'Maplewood - Emily Bay (N&C2021)', artist: 'Maplewood', genre: '' },
	{ id: '7Py3A39a4fA', start: 1, end: 171, title: 'Silent Sessions - Live music through Silent Disco equipment feat. Molly Devine!', artist: 'Silent Sessions', genre: '' },
	{ id: 'h_E9HyfUxec', start: 1, end: 234, title: 'Mia - Out of The Cocoon', artist: 'Mia', genre: '' },
	{ id: 'awe_gbL7650', start: 1, end: 203, title: 'Both Sides of the Line - Surfing in the Rain', artist: 'Both Sides of the Line', genre: '' },
	{ id: 'EpjDdUf72ss', start: 1, end: 121, title: 'Autumn Online - Me (N&C2021)', artist: 'Autumn Online', genre: '' },
	{ id: 'mftHvlZEbSk', start: 1, end: 199, title: 'Pop Tops - Motorbike (N&C2021)', artist: 'Pop Tops', genre: '' },
	{ id: '_yjUgMJSp-Y', start: 1, end: 3763, title: 'Save Live Music! The trials of live music with Dave and Fairleigh - Big Scenes, Small Cities.', artist: 'Save Live Music! The trials of live music with Dave and Fairleigh', genre: '' },
	{ id: 'AH21HEvGJYs', start: 1, end: 329, title: 'Julian Temple - Fundraiser for the Dog With Two Tails', artist: 'Julian Temple', genre: '' },
	{ id: 'p85FyzC3uP8', start: 1, end: 158, title: 'Before The Snooze - Find The Time', artist: 'Before The Snooze', genre: '' },
	{ id: 'UPoH4LaGsbQ', start: 1, end: 245, title: 'Jae Bedford - Lost In Cuba (N&C2021)', artist: 'Jae Bedford', genre: '' },
	{ id: 'YrIcF85Rn90', start: 1, end: 212, title: 'The Doll Drums - Stop Insulting Me', artist: 'The Doll Drums', genre: '' },
	{ id: '8Sy20KyoBAc', start: 1, end: 354, title: 'Catherine KS - Never Make Someone Else A Priority When All You are to Them is an Option', artist: 'Catherine KS', genre: '' },
	{ id: 'uD5MttrJqtI', start: 1, end: 208, title: 'Mia - Sky People', artist: 'Mia', genre: '' },
	{ id: '7RxntnwjJ3M', start: 1, end: 293, title: 'Sense of Time - You Said (N&C22)', artist: 'Sense of Time', genre: '' },
	{ id: 'AvCw1J-_Ly0', start: 1, end: 278, title: 'Trent Hawthorne - 11:00', artist: 'Trent Hawthorne', genre: '' },
	{ id: 'rhRXEfbkoCs', start: 1, end: 335, title: 'Mia - Collide - Nook & Cranny 2018 warm up', artist: 'Mia', genre: '' },
	{ id: 'W8zDLdeohZQ', start: 1, end: 125, title: 'Rus Ruckus - Saturday on the River (N&C2021)', artist: 'Rus Ruckus', genre: '' },
	{ id: 'KxQggz_hfCo', start: 1, end: 185, title: 'Paul Allen - Am I Flying', artist: 'Paul Allen', genre: '' },
	{ id: '87Du_PHgj74', start: 1, end: 221, title: 'Southern Consort of Voices - O Radiant Dawn', artist: 'Southern Consort of Voices', genre: '' },
	{ id: 'ADwiDq-NNb0', start: 1, end: 209, title: 'Concrete Grady Angels Walk Among Us', artist: 'Concrete Grady Angels Walk Among Us', genre: '' },
	{ id: 'iCpkOqQE0ME', start: 1, end: 151, title: 'Paul S Allen - Sleep', artist: 'Paul S Allen', genre: '' },
	{ id: 'L61l6hABLwc', start: 1, end: 236, title: 'The Doo Rays - Time On Your Hands', artist: 'The Doo Rays', genre: '' },
	{ id: '5lefWQM9Aig', start: 1, end: 212, title: 'Europa Kid - Desmond Morrissey (N&C2021)', artist: 'Europa Kid', genre: '' },
	{ id: 'k9cjdFqtWFc', start: 1, end: 311, title: 'The Mentalist Collective - Need a little time away - Nook and Cranny Festival 2016', artist: 'The Mentalist Collective', genre: '' },
	{ id: 'enAFFuV7vKo', start: 1, end: 179, title: 'Deej Cooper - England\'s Not the Same (N&C2021)', artist: 'Deej Cooper', genre: '' },
	{ id: 'mRDLvchielU', start: 1, end: 203, title: 'Hana Fahy - Logic And Chemistry', artist: 'Hana Fahy', genre: '' },
	{ id: 'QqmDlRihCPM', start: 1, end: 164, title: 'Darryl Baser - Pretty', artist: 'Darryl Baser', genre: '' },
	{ id: 'nwHjz45y4Ls', start: 1, end: 162, title: 'Leigham - Strange Creature (N&C2021)', artist: 'Leigham', genre: '' },
	{ id: 'vcAJ1i6OePo', start: 1, end: 203, title: 'Undecided - Purple', artist: 'Undecided', genre: '' },
	{ id: 'Jd6WzwbOpDo', start: 1, end: 254, title: 'Neive Strang - Is It So Wrong', artist: 'Neive Strang', genre: '' },
	{ id: 'JVzbdZ79LIQ', start: 1, end: 133, title: 'Inge Andrew - Heart Attack', artist: 'Inge Andrew', genre: '' },
	{ id: '0Rojg1_UXjA', start: 1, end: 210, title: 'Sharkbait - Calm Blue Ocean', artist: 'Sharkbait', genre: '' },
	{ id: '8Q-XPiqEzVU', start: 1, end: 194, title: 'Folk Infusion & The Lady - Little Miracle (N&C2021)', artist: 'Folk Infusion & The Lady', genre: '' },
	{ id: 'WImSgUXMGC0', start: 1, end: 1446, title: 'Big Scenes, Small Cities - Gareth Stack (The Bleeders)', artist: 'Big Scenes, Small Cities', genre: '' },
	{ id: 'm4vYRzH6A3k', start: 1, end: 174, title: 'The Generators - Keep Our Business to Yourself', artist: 'The Generators', genre: '' },
	{ id: '4n2Uy-rTqzk', start: 1, end: 217, title: 'Darryl Baser - Everyone Has Their Own Special Selfie', artist: 'Darryl Baser', genre: '' },
	{ id: '5JD4GksdVDI', start: 1, end: 236, title: '2022 Nook And Cranny Music Festival - Plaza Party Overview', artist: '2022 Nook And Cranny Music Festival', genre: '' },
	{ id: 'P2wBefa6jgA', start: 1, end: 377, title: 'Mosaic Sky - Fast and Slow', artist: 'Mosaic Sky', genre: '' },
	{ id: 'NAwmcOmdQnk', start: 1, end: 161, title: 'Kartharticus - We Shall Not Be Moved', artist: 'Kartharticus', genre: '' },
	{ id: 'Z8Psvppc95g', start: 1, end: 309, title: 'The Phil Corfield Band - Looking to Fly', artist: 'The Phil Corfield Band', genre: '' },
	{ id: 'izH9vtwxfL4', start: 1, end: 224, title: 'Robots In Love - Dunedin', artist: 'Robots In Love', genre: '' },
	{ id: '2miDiIPMvyc', start: 1, end: 231, title: 'The Mentalist Collective - Running Through Long Grass', artist: 'The Mentalist Collective', genre: '' },
	{ id: 'xeO7A22vEOA', start: 1, end: 401, title: 'Solopsist, Asleep - Slow Capsize (Part 1)', artist: 'Solopsist, Asleep', genre: '' },
	{ id: 'ricfO0JAPlo', start: 1, end: 136, title: 'Dr Marigaux - Strange City', artist: 'Dr Marigaux', genre: '' },
	{ id: 'p76_0-K09A0', start: 1, end: 345, title: 'Celluloid Bikers - FourandSix', artist: 'Celluloid Bikers', genre: '' },
	{ id: 'Cm7eA1wdd38', start: 1, end: 281, title: 'Keira Wallace - Lemon Eyes (N&C2021)', artist: 'Keira Wallace', genre: '' },
	{ id: '23boJ6a9hq0', start: 1, end: 220, title: 'Europa Kid - Comforting Friend', artist: 'Europa Kid', genre: '' },
	{ id: '18Re4TUsbk0', start: 1, end: 157, title: 'James Dignan - Gone Too Soon', artist: 'James Dignan', genre: '' },
	{ id: '2_FcsivxaaA', start: 1, end: 278, title: 'Kym Alisha - Dance With My Father', artist: 'Kym Alisha', genre: '' },
	{ id: 'TZvLIq47Yck', start: 1, end: 269, title: 'Graham Tamati - Early Morning Rain', artist: 'Graham Tamati', genre: '' },
	{ id: 'lcVV4KysXSM', start: 1, end: 144, title: 'Matt Langley Things could be better', artist: 'Matt Langley Things could be better', genre: '' },
	{ id: 'DZOBlY_fhgI', start: 1, end: 230, title: 'The Wandering Gypsy Jukebox - Intro Jam (N&C2021)', artist: 'The Wandering Gypsy Jukebox', genre: '' },
	{ id: 'YYZvtyLqqK8', start: 1, end: 113, title: 'Shelly4Kids - Tara the Tuatara (N&C2021)', artist: 'Shelly4Kids', genre: '' },
	{ id: 'Qav72hAPyyY', start: 1, end: 211, title: 'Dunedin Scottish Fiddle Orchestra - Stormy Blues (N&C2021)', artist: 'Dunedin Scottish Fiddle Orchestra', genre: '' },
	{ id: 'FIBX4qIIMDY', start: 1, end: 233, title: 'Prophet Hens - Nook and Cranny Festival 2016', artist: 'Prophet Hens', genre: '' },
	{ id: 'osEQPCp76IY', start: 1, end: 306, title: 'Bronwyn - Hide Away - Nook & Cranny 2018 warm up', artist: 'Bronwyn', genre: '' },
	{ id: 'RNVfp1AMYag', start: 1, end: 219, title: 'Dunedin Rock Choir - I Got You (Split Enz)', artist: 'Dunedin Rock Choir', genre: '' },
	{ id: '0Lfyqryfbzs', start: 1, end: 217, title: 'Tom Csima - Never Whole', artist: 'Tom Csima', genre: '' },
	{ id: 'yfXwFt10UMU', start: 1, end: 255, title: 'Deej Cooper - If I Were Anything', artist: 'Deej Cooper', genre: '' },
	{ id: 'SmYFpRUBTpY', start: 1, end: 256, title: 'Pearl Street - Billie With The Blue Hair (N&C2021)', artist: 'Pearl Street', genre: '' },
	{ id: '8_JIPvIhanw', start: 1, end: 222, title: 'Jackson Caine - Trying to Attract That Girl (N&C2021)', artist: 'Jackson Caine', genre: '' },
	{ id: 'a9hZPTGIfgI', start: 1, end: 160, title: 'The Pottley Blues Collective - Don\'t Walk Away (N&C22)', artist: 'The Pottley Blues Collective', genre: '' },
	{ id: 'WmOtWz8l7t4', start: 1, end: 190, title: 'Worn Out Jumper - New Love', artist: 'Worn Out Jumper', genre: '' },
	{ id: 'jIEj0abGYCk', start: 1, end: 256, title: 'Boaz Anema - So Real', artist: 'Boaz Anema', genre: '' },
	{ id: 'eYnJcCK0sDU', start: 1, end: 260, title: 'The Acoustic Paintings - Rabbit', artist: 'The Acoustic Paintings', genre: '' },
	{ id: '-pab-_RlpXE', start: 1, end: 244, title: 'Seafog - Dig', artist: 'Seafog', genre: '' },
	{ id: '5Elf-jP14ig', start: 1, end: 228, title: 'The Nook & Cranny Music Festival 2018 - Overview', artist: 'The Nook & Cranny Music Festival 2018', genre: '' },
	{ id: 'mh8z7aG-zEU', start: 1, end: 216, title: 'Concrete Grady - Bad Apples', artist: 'Concrete Grady', genre: '' },
	{ id: 'gC-YubPVuqg', start: 1, end: 86, title: 'Barabajagal - Hippopotamus', artist: 'Barabajagal', genre: '' },
	{ id: 'olupDDJm8yc', start: 1, end: 188, title: 'Cathy Zeng - Darkest Hours', artist: 'Cathy Zeng', genre: '' },
	{ id: '1YNlZxsqQYE', start: 1, end: 208, title: 'Jae Bedford - Moving On (N&C22)', artist: 'Jae Bedford', genre: '' },
	{ id: 'OiUOW7Y-VHU', start: 1, end: 156, title: 'The Dunedin Scottish Fiddle Orchestra', artist: 'The Dunedin Scottish Fiddle Orchestra', genre: '' },
	{ id: 'KpdfMckytgo', start: 1, end: 202, title: 'David Wang - Royals', artist: 'David Wang', genre: '' },
	{ id: 'LynD618h9iQ', start: 1, end: 172, title: 'Person Will - Intro/Podium Medley', artist: 'Person Will', genre: '' },
	{ id: 'IMPuYqIGuA8', start: 1, end: 182, title: 'Double Trouble - Taste of Gin', artist: 'Double Trouble', genre: '' },
	{ id: 'GNnK9vjroMk', start: 1, end: 216, title: 'Adie K - Piwakawaka', artist: 'Adie K', genre: '' },
	{ id: 'KMJDYDHlYdE', start: 1, end: 262, title: 'Melissa & The Dr - Country Girl (N&C 2022)', artist: 'Melissa & The Dr', genre: '' },
	{ id: 'QDnjQd-Co-I', start: 1, end: 223, title: 'Chasing Chords - Personally', artist: 'Chasing Chords', genre: '' },
	{ id: '75vF1wXalGQ', start: 1, end: 157, title: 'Katharticus - Wilson Parking', artist: 'Katharticus', genre: '' },
	{ id: 'FzRpuqt_utk', start: 1, end: 278, title: 'Nook & Cranny Festival 2019 - Overview of the world\'s loudest library', artist: 'Nook & Cranny Festival 2019', genre: '' },
	{ id: 'VMkXRFJ_VrQ', start: 1, end: 242, title: 'Holly McPhee - Magpie', artist: 'Holly McPhee', genre: '' },
	{ id: 'E6QI73Kc0l8', start: 1, end: 159, title: 'Paul S Allen - And He Flies (N&C2021)', artist: 'Paul S Allen', genre: '' },
	{ id: 'omvwvcEK66k', start: 1, end: 169, title: 'The Generators - Riding In The Moonlight (Howlin\' Wolf)', artist: 'The Generators', genre: '' },
	{ id: 'ZN7JR-Lr0ew', start: 1, end: 199, title: 'Humboldt County - Foggy Afternoon', artist: 'Humboldt County', genre: '' },
	{ id: 'vehoceIDHHs', start: 1, end: 178, title: 'Emi Sharma - Thirteen', artist: 'Emi Sharma', genre: '' },
	{ id: '7twtbU97v0w', start: 1, end: 296, title: 'Bo & The Constrictors - Woo Hoo (N&C2021)', artist: 'Bo & The Constrictors', genre: '' },
	{ id: 'hAtZZv3dfFI', start: 1, end: 217, title: 'Both Sides of the Line - La La Land', artist: 'Both Sides of the Line', genre: '' },
	{ id: 'QqdSl2Qq29w', start: 1, end: 8015, title: 'Dunedin House Concert - Mickey & Michelle_13th Jan 2023', artist: 'Dunedin House Concert', genre: '' },
	{ id: 'iKOx_n4PQcM', start: 1, end: 87, title: 'The Flukes - Untouchable Girls - Nook and Cranny Festival 2016', artist: 'The Flukes', genre: '' },
	{ id: 'ArOgPfCqk8A', start: 1, end: 277, title: 'Kathartipuss - Vossons (N&C2021)', artist: 'Kathartipuss', genre: '' },
	{ id: 'cspmdD9RTYU', start: 1, end: 261, title: 'Idol Frets - You Ought To Be In Love', artist: 'Idol Frets', genre: '' },
	{ id: '2om93xxXTF4', start: 1, end: 188, title: 'Cassandra Scott - Thinking \'Bout You (Dua Lipa)', artist: 'Cassandra Scott', genre: '' },
	{ id: '8b2gA9-VO0E', start: 1, end: 1147, title: 'William Henry Meung - Science Fiction Garden for the Blind', artist: 'William Henry Meung', genre: '' },
	{ id: 'L9G7DIOkX-0', start: 1, end: 177, title: 'Sam Beal - Happens (N&C2021)', artist: 'Sam Beal', genre: '' },
	{ id: 'KXCtAxKM234', start: 1, end: 254, title: 'Haszari - Kip Kapsalon/Maenyb', artist: 'Haszari', genre: '' },
	{ id: '4e07BbCEvn8', start: 1, end: 173, title: 'The Vortz - Funk It - Nook and Cranny Festival 2016', artist: 'The Vortz', genre: '' },
	{ id: 'UqZ85gUJsbo', start: 1, end: 231, title: 'Bronwyn - Just A Little Chipped', artist: 'Bronwyn', genre: '' },
	{ id: '9aVmRhSXwhM', start: 1, end: 250, title: 'Madeleine Howard - A Song For You', artist: 'Madeleine Howard', genre: '' },
	{ id: 'eTftpuRoDB4', start: 1, end: 121, title: 'Ashes - Offline (Little Green Dot)', artist: 'Ashes', genre: '' },
	{ id: '0ME13clP76Q', start: 1, end: 382, title: 'Dunedin Scottish Fiddle Orchestra - Cathcart', artist: 'Dunedin Scottish Fiddle Orchestra', genre: '' },
	{ id: '2QOKu7cyrU8', start: 1, end: 254, title: 'Sun Veins - Needy', artist: 'Sun Veins', genre: '' },
	{ id: 'teFObegx5a4', start: 1, end: 267, title: 'One Day Sane - You Hey', artist: 'One Day Sane', genre: '' },
	{ id: '8rXd7skgWOQ', start: 1, end: 202, title: 'Boaz Anema - Backwater - Nook & Cranny 2018 warm up', artist: 'Boaz Anema', genre: '' },
	{ id: 'ZC0OHXinBbE', start: 1, end: 203, title: 'Seedy - Right For Me', artist: 'Seedy', genre: '' },
	{ id: 'ta3MF95UsbQ', start: 1, end: 189, title: 'Ronel Hunter - Little White Pill', artist: 'Ronel Hunter', genre: '' },
	{ id: 'vH5c1xeDpvE', start: 1, end: 392, title: 'Saltmarsh - Waves', artist: 'Saltmarsh', genre: '' },
	{ id: 'md2nqrNyJt8', start: 1, end: 188, title: 'Both Sides of the Line - Endlessly Facinated', artist: 'Both Sides of the Line', genre: '' },
	{ id: 'v6LFYNCGHbM', start: 1, end: 221, title: 'Katharticus - Inner Groan', artist: 'Katharticus', genre: '' },
	{ id: 'u-3OxqmHWTE', start: 1, end: 294, title: 'Saurian - Tyre Tracks (In the Sky) (N&C2021)', artist: 'Saurian', genre: '' },
	{ id: 'RqDdcDVlEQQ', start: 1, end: 178, title: 'Certainty - Older', artist: 'Certainty', genre: '' },
	{ id: 'gqPQFna2xA0', start: 1, end: 222, title: 'Tahu & The Takahes - Billy King (N&C22)', artist: 'Tahu & The Takahes', genre: '' },
	{ id: 'TkNTcw0BD5A', start: 1, end: 263, title: 'Scott J Mason - Won\'t Come Back', artist: 'Scott J Mason', genre: '' },
	{ id: '8cRq_9p7uYI', start: 1, end: 189, title: 'Shelley J - Chicken Song', artist: 'Shelley J', genre: '' },
	{ id: 'JwnFIh8d1KM', start: 1, end: 174, title: 'Melissa and the Dr. - Rain Fall On Me (Donna Dean)', artist: 'Melissa and the Dr.', genre: '' },
	{ id: 'lHrER3ipDfs', start: 1, end: 178, title: 'Before The Snooze - Set Me Free', artist: 'Before The Snooze', genre: '' },
	{ id: 'q-PnZIrqieo', start: 1, end: 191, title: 'Pearl Street - Invisible Threads', artist: 'Pearl Street', genre: '' },
	{ id: '2uCyhR4xOzo', start: 1, end: 210, title: 'darryl baser - St Kilda Reflections (for Nick)(N&C2021)', artist: 'darryl baser', genre: '' },
	{ id: '9w-QtC0ktkA', start: 1, end: 425, title: 'Ronnie Stash - One for the Road', artist: 'Ronnie Stash', genre: '' },
	{ id: 'vtZRqoHPtSg', start: 1, end: 173, title: 'The Acoustic Paintings - Bonsai (N&C2021)', artist: 'The Acoustic Paintings', genre: '' },
	{ id: 'M_gY2XCApgU', start: 1, end: 159, title: 'Melissa and the Dr - Mama Bear', artist: 'Melissa and the Dr', genre: '' },

// Total: 208 tracks, 16:38:21
];
